name: UPM on npsjs.com
on:
  push:
    branches:    
      - 'main'
      - 'releases/**'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        registry-url: 'https://registry.npmjs.org'
    - run: npm publish
      working-directory: Packages/tokyo.tichise.ink-decal
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
